import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        coolors: {
          non_photo_blue: {
            DEFAULT: "#a3e7fc",
            100: "#023e50",
            200: "#057ca0",
            300: "#07baf0",
            400: "#51d2fa",
            500: "#a3e7fc",
            600: "#b4ecfd",
            700: "#c7f1fd",
            800: "#d9f5fe",
            900: "#ecfafe",
          },
          emerald: {
            DEFAULT: "#26c485",
            100: "#08271b",
            200: "#0f4f35",
            300: "#177650",
            400: "#1e9e6b",
            500: "#26c485",
            600: "#46dca0",
            700: "#74e5b8",
            800: "#a2edcf",
            900: "#d1f6e7",
          },
          charcoal: {
            DEFAULT: "#454851",
            100: "#0e0e10",
            200: "#1b1c20",
            300: "#292b30",
            400: "#363940",
            500: "#454851",
            600: "#656a77",
            700: "#8a8e9b",
            800: "#b1b4bc",
            900: "#d8d9de",
          },
          lavender_blush: {
            DEFAULT: "#fceff9",
            100: "#521043",
            200: "#a51f85",
            300: "#dc49ba",
            400: "#ec9cd9",
            500: "#fceff9",
            600: "#fcf1fa",
            700: "#fdf5fb",
            800: "#fef8fc",
            900: "#fefcfe",
          },
          peach_yellow: {
            DEFAULT: "#ffe1a8",
            100: "#553700",
            200: "#a96e00",
            300: "#fea500",
            400: "#ffc354",
            500: "#ffe1a8",
            600: "#ffe7ba",
            700: "#ffedcb",
            800: "#fff3dc",
            900: "#fff9ee",
          },
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      gridTemplateRows: {
        "[auto,auto,1fr]": "auto auto 1fr",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
